#! /usr/bin/env python

import roslib
roslib.load_manifest('autonomous_car')
import rospy
import actionlib

# Decide if necessery and define
from autonomous_nav.msg import NavigationAction, NavigationGoal

class NavigationServer:
  def __init__(self):
    self.server = actionlib.SimpleActionServer('doNavigation', DoDishesAction, self.execute, False)
    self.server.start()

  def execute(self, goal):
    # Do lots of awesome groundbreaking robot stuff here -> EXECUTE GOAL
    #http://wiki.ros.org/actionlib


    self.server.set_succeeded()


if __name__ == '__main__':
  rospy.init_node('navigation_server')
  server = NavigationServer()
  rospy.spin()
